/**
 * The font is DATA: each character is its 5 rows, drawn as you see it.
 * To change how a digit looks, edit its picture. To add a character
 * (a-f for hex clocks?), add an entry — nothing else changes.
 */
export const FONT = {
  '0': ['###',
        '# #',
        '# #',
        '# #',
        '###'],
  '1': ['  #',
        '  #',
        '  #',
        '  #',
        '  #'],
  '2': ['###',
        '  #',
        '###',
        '#  ',
        '###'],
  '3': ['###',
        '  #',
        '###',
        '  #',
        '###'],
  '4': ['# #',
        '# #',
        '###',
        '  #',
        '  #'],
  '5': ['###',
        '#  ',
        '###',
        '  #',
        '###'],
  '6': ['###',
        '#  ',
        '###',
        '# #',
        '###'],
  '7': ['###',
        '  #',
        '  #',
        '  #',
        '  #'],
  '8': ['###',
        '# #',
        '###',
        '# #',
        '###'],
  '9': ['###',
        '# #',
        '###',
        '  #',
        '###'],
  ':': ['   ',
        ' # ',
        '   ',
        ' # ',
        '   '],
};

export const FONT_HEIGHT = 5;
